'use client';
import { useEffect,useMemo,useState } from 'react'; import { CalendarDays,Check,ChevronRight,Clock3,History,Home,Lock,LogOut,Medal,RefreshCw,Settings,Shield,Target,UserRound,Users } from 'lucide-react';
type Data=any; type Tab='picks'|'week'|'season'|'history'|'profile'|'admin';
const fmt=(v:string)=>new Intl.DateTimeFormat('es-MX',{weekday:'long',hour:'numeric',minute:'2-digit'}).format(new Date(v));
const initials=(name?:string)=>name?.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()||'NFL';

export default function Page(){const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[tab,setTab]=useState<Tab>('picks');const[error,setError]=useState('');
 const load=async(query='')=>{setLoading(true);const r=await fetch('/api/data'+query,{cache:'no-store'});if(r.ok)setData(await r.json());else setData(null);setLoading(false)};useEffect(()=>{load()},[]);
 if(loading)return <Shell><div className="skeleton hero"/><div className="skeleton card"/><div className="skeleton card"/></Shell>;
 if(!data)return <Login onDone={load}/>; if(!data.user.nickname)return <ProfileSetup onDone={load}/>;
 const tabs:[Tab,string,any][]=[['picks','Mis Picks',Target],['week','Semana',Users],['season','Temporada',Medal],['history','Historial',History],['profile','Perfil',UserRound]];
 return <><Shell><Header data={data}/>{error&&<div className="toast error">{error}</div>}{tab==='picks'&&<Picks data={data} reload={load} fail={setError}/>} {tab==='week'&&<Week data={data}/>} {tab==='season'&&<Season data={data}/>} {tab==='history'&&<HistoryView data={data} load={load}/>} {tab==='profile'&&<Profile data={data} reload={load}/>} {tab==='admin'&&<Admin data={data} reload={load}/>}</Shell><nav className="bottom-nav">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={20}/><span>{label}</span></button>)}{data.user.is_admin&&<button className={tab==='admin'?'active':''} onClick={()=>setTab('admin')}><Settings size={20}/><span>Admin</span></button>}</nav></>}

function Shell({children}:{children:React.ReactNode}){return <main className="app-shell">{children}</main>}
function Login({onDone}:{onDone:()=>void}){const[email,setEmail]=useState('');const[busy,setBusy]=useState(false);const[err,setErr]=useState('');const submit=async(e:any)=>{e.preventDefault();setBusy(true);const r=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email})});const j=await r.json();setBusy(false);if(!r.ok)setErr(j.error);else onDone()};return <div className="login"><div className="brand-ball">NFL</div><p className="eyebrow">TEMPORADA 2026</p><h1>La Quiniela</h1><p>Elige a tus ganadores. Compite con tus amigos. Presume el marcador.</p><form onSubmit={submit} className="login-card"><label>Tu correo</label><input type="email" placeholder="tu@correo.com" value={email} onChange={e=>setEmail(e.target.value)} required/><button className="primary" disabled={busy}>{busy?'Entrando…':'Entrar a la quiniela'}<ChevronRight size={19}/></button>{err&&<p className="form-error">{err}</p>}</form><small>Acceso privado · Sólo participantes invitados</small></div>}
function ProfileSetup({onDone}:{onDone:()=>void}){const[nickname,setNickname]=useState('');const[avatar,setAvatar]=useState<string|null>(null);const[err,setErr]=useState('');const upload=async(e:any)=>{const f=e.target.files?.[0];if(!f)return;const fd=new FormData();fd.append('file',f);const r=await fetch('/api/avatar',{method:'POST',body:fd});const j=await r.json();if(r.ok)setAvatar(j.url);else setErr(j.error)};const save=async(e:any)=>{e.preventDefault();const r=await fetch('/api/profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({nickname,avatarUrl:avatar})});const j=await r.json();r.ok?onDone():setErr(j.error)};return <div className="login"><div className="avatar xl">{avatar?<img src={avatar} alt="Vista previa"/>:<UserRound/>}</div><p className="eyebrow">BIENVENIDO AL EQUIPO</p><h1>Crea tu perfil</h1><p>Así te reconocerán los demás jugadores.</p><form className="login-card" onSubmit={save}><label>Apodo</label><input value={nickname} onChange={e=>setNickname(e.target.value)} minLength={2} maxLength={24} placeholder="Ej. El Coach" required/><label className="upload">Tomar o elegir foto<input hidden type="file" accept="image/jpeg,image/png,image/webp" capture="user" onChange={upload}/></label><button className="primary">Comenzar</button>{err&&<p className="form-error">{err}</p>}</form></div>}
function Header({data}:{data:Data}){return <header><div><p className="eyebrow">LA QUINIELA NFL</p><h2>Hola, {data.user.nickname}</h2></div><Avatar user={data.user}/></header>}
function Avatar({user}:{user:any}){return <div className="avatar">{user.avatar_url?<img src={user.avatar_url} alt={`Foto de ${user.nickname}`}/>:initials(user.nickname)}</div>}
function Picks({data,reload,fail}:{data:Data,reload:()=>void,fail:(x:string)=>void}){const w=data.week;if(!w)return <Empty/>;const locked=Date.now()>=Date.parse(w.first_kickoff)||w.manually_locked;const mine=(id:string)=>data.picks.find((p:any)=>p.user_id===data.user.id&&p.game_id===id)?.selected_team;const completed=data.games.filter((g:any)=>mine(g.id)).length;const pick=async(gameId:string,team:string)=>{const r=await fetch('/api/picks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({gameId,team})});const j=await r.json();if(r.ok)reload();else fail(j.error)};return <section><div className="week-hero"><div><p>{data.season.year} · {w.week_type==='preseason'?'PRETEMPORADA':'TEMPORADA'}</p><h1>{w.label}</h1><span><Clock3 size={15}/>{locked?'Picks cerrados':`Cierran ${fmt(w.first_kickoff)}`}</span></div><div className="progress-ring"><b>{completed}</b><small>de {data.games.length}</small></div></div><div className="section-title"><div><h3>Partidos</h3><p>{locked?'Tus selecciones están bloqueadas':`${data.games.length-completed} picks pendientes`}</p></div>{locked&&<Lock size={18}/>}</div>{data.games.map((g:any)=><GameCard key={g.id} game={g} selected={mine(g.id)} locked={locked} pick={pick}/>)}<Tiebreaker data={data} reload={reload}/></section>}
function GameCard({game,selected,locked,pick}:{game:any,selected?:string,locked:boolean,pick:(id:string,t:string)=>void}){return <article className="game-card"><div className="game-meta"><span>{fmt(game.kickoff_at)}</span><span>{game.status==='final'?'Final':game.status==='in_progress'?'En vivo':'Programado'}</span></div><button disabled={locked} className={`team ${selected===game.away_team?'selected':''}`} onClick={()=>pick(game.id,game.away_team)}><img src={game.away_logo||`https://a.espncdn.com/i/teamlogos/nfl/500/${game.away_team.toLowerCase()}.png`} alt={`Logo ${game.away_name}`}/><span><b>{game.away_name}</b><small>{game.away_team}</small></span>{game.away_score!=null&&<strong>{game.away_score}</strong>}{selected===game.away_team&&<i><Check size={15}/></i>}</button><div className="versus">VS</div><button disabled={locked} className={`team ${selected===game.home_team?'selected':''}`} onClick={()=>pick(game.id,game.home_team)}><img src={game.home_logo||`https://a.espncdn.com/i/teamlogos/nfl/500/${game.home_team.toLowerCase()}.png`} alt={`Logo ${game.home_name}`}/><span><b>{game.home_name}</b><small>{game.home_team} · LOCAL</small></span>{game.home_score!=null&&<strong>{game.home_score}</strong>}{selected===game.home_team&&<i><Check size={15}/></i>}</button></article>}
function Tiebreaker({data,reload}:{data:Data,reload:()=>void}){const own=data.tiebreakers.find((t:any)=>t.user_id===data.user.id)?.prediction??'';const[v,setV]=useState(own);const open=Date.now()<Date.parse(data.week.last_kickoff);const save=async()=>{await fetch('/api/tiebreaker',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({weekId:data.week.id,prediction:Number(v)})});reload()};return <article className="tie-card"><p className="eyebrow">DESEMPATE</p><h3>¿Cuántos puntos anotarán entre ambos equipos en el último partido?</h3><div><input aria-label="Puntos totales" type="number" min="0" max="200" disabled={!open} value={v} onChange={e=>setV(e.target.value)} onBlur={save}/><span>puntos</span></div><small>{open?`Puedes modificarlo hasta ${fmt(data.week.last_kickoff)}`:'El desempate está cerrado'}</small></article>}
function Week({data}:{data:Data}){const reveal=Date.now()>=Date.parse(data.week.first_kickoff);return <section><Title title="Esta Semana" subtitle={reveal?'Los picks ya son públicos':'Las selecciones se revelan al cierre'}/>{!reveal&&<div className="notice"><Shield/> Nadie puede ver los picks de otros antes del cierre.</div>}<div className="standings">{data.weekly.map((r:any,i:number)=><div className="standing" key={r.userId}><b>{i+1}</b><Avatar user={{nickname:r.nickname,avatar_url:r.avatarUrl}}/><span><strong>{r.nickname}</strong><small>{reveal?`${r.correct} aciertos · ${r.pending} pendientes`:(r.pending===0?'Listo':'Pendiente')}</small></span>{r.winner&&<Medal className="gold"/>}</div>)}</div>{reveal&&<><Title title="Picks por partido" subtitle="Selecciones de todos los jugadores"/>{data.games.map((g:any)=><article className="grid-card" key={g.id}><h4>{g.away_team} <span>vs</span> {g.home_team}</h4>{data.players.map((p:any)=>{const x=data.picks.find((q:any)=>q.user_id===p.id&&q.game_id===g.id);return <div key={p.id}><span>{p.nickname}</span><b>{x?.selected_team||'—'}</b></div>})}</article>)}</>}</section>}
function Season({data}:{data:Data}){return <section><Title title="Clasificación" subtitle={`${data.season.year} · La carrera por el campeonato`}/><div className="podium"><Medal/><b>Tabla de temporada</b><small>Pretemporada no incluida</small></div><div className="standings">{data.seasonStandings.map((r:any)=><div className="standing" key={r.userId}><b className="rank">{r.rank}</b><Avatar user={{nickname:r.nickname,avatar_url:r.avatarUrl}}/><span><strong>{r.nickname}</strong><small>{r.weeklyWins} victorias semanales</small></span><em><b>{r.correct}</b><small>aciertos</small></em></div>)}</div></section>}
function HistoryView({data,load}:{data:Data,load:(q:string)=>void}){return <section><Title title="Historial" subtitle="Revive cada semana de la temporada"/><select className="select" value={data.season.year} onChange={e=>load(`?season=${e.target.value}`)}>{data.seasons.map((s:any)=><option key={s.id}>{s.year}</option>)}</select><div className="week-list">{data.weeks.map((w:any)=><button key={w.id} onClick={()=>load(`?season=${data.season.year}&week=${w.id}`)}><CalendarDays/><span><b>{w.label}</b><small>{w.week_type==='preseason'?'Pretemporada':'Temporada oficial'}</small></span><ChevronRight/></button>)}</div></section>}
function Profile({data,reload}:{data:Data,reload:()=>void}){const[nickname,setNickname]=useState(data.user.nickname);const save=async()=>{await fetch('/api/profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({nickname,avatarUrl:data.user.avatar_url})});reload()};return <section><Title title="Mi Perfil" subtitle="Tu identidad en la quiniela"/><div className="profile-card"><Avatar user={data.user}/><label>Apodo<input value={nickname} onChange={e=>setNickname(e.target.value)}/></label><button className="primary" onClick={save}>Guardar cambios</button><button className="ghost danger" onClick={async()=>{await fetch('/api/auth',{method:'DELETE'});location.reload()}}><LogOut/>Cerrar sesión</button></div></section>}
function Admin({data,reload}:{data:Data,reload:()=>void}){const[pin,setPin]=useState('');const[email,setEmail]=useState('');const[msg,setMsg]=useState('');const act=async(action:string,payload:any={})=>{const r=await fetch('/api/admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pin,action,payload})});const j=await r.json();setMsg(r.ok?'Acción completada':j.error);if(r.ok)reload()};const week=data.week;return <section><Title title="Administrador" subtitle="Control simple de la quiniela"/><div className="admin-card"><label>PIN de administrador<input type="password" value={pin} onChange={e=>setPin(e.target.value)}/></label></div><div className="admin-card"><h3>Participantes</h3><label>Correo autorizado<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="primary" onClick={()=>act('addUser',{email})}>Agregar correo</button></div><div className="admin-card"><h3>Datos NFL</h3><button className="secondary" onClick={()=>act('sync',{year:data.season?.year})}><RefreshCw/>Sincronizar temporada</button><button className="secondary" onClick={()=>act('sync',{year:data.season?.year})}><RefreshCw/>Actualizar resultados</button></div><div className="admin-card"><h3>Semana activa</h3>{week&&data.season?<><select className="select" onChange={e=>act('setWeek',{seasonId:data.season.id,weekId:e.target.value})} value={week.id}>{data.weeks.map((w:any)=><option value={w.id} key={w.id}>{w.label}</option>)}</select><button className="secondary" onClick={()=>act('toggleLock',{weekId:week.id,locked:!week.manually_locked})}>{week.manually_locked?'Desbloquear semana':'Bloquear semana'}</button></>:<p className="form-error">No hay semanas disponibles. Ingresa el PIN y sincroniza la temporada.</p>}</div>{msg&&<div className="toast">{msg}</div>}</section>}
function Title({title,subtitle}:{title:string,subtitle:string}){return <div className="page-title"><h1>{title}</h1><p>{subtitle}</p></div>};function Empty(){return <div className="empty"><CalendarDays/><h2>No hay partidos todavía</h2><p>Un administrador debe sincronizar la temporada.</p></div>}
